name: Daily JS Challenge
description: Template for daily JavaScript challenge issues.
body:
  - type: markdown
    attributes:
      value: |
        ## Day X: JavaScript Challenge

        Describe the challenge for today.

  - type: textarea
    id: progress
    attributes:
      label: Progress
      description: What did you accomplish today?
      placeholder: I completed...
    validations:
      required: true
