# .github/workflows/auto-100-days-js.yml
name: Auto‑populate 100 Days of JS
on:
  workflow_dispatch:

permissions:
  contents: write     # required for gh CLI to write files (used by checkout)
  issues: write       # to create issues

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Create Weekly Milestones
        id: milestones
        run: |
          for WEEK in $(seq 1 14); do
            gh api repos/${{ github.repository }}/milestones \
              -f title="Week $WEEK" \
              -f description="Days $(( (WEEK-1)*7 + 1 ))–$(( WEEK*7 ))" \
              --jq '.number' >> ms.txt
          done
          echo "MILESTONE_LIST=$(paste -sd, ms.txt)" >> $GITHUB_ENV

      - name: Create Day Issues & Add to Project
        run: |
          IFS=, read -r -a MILESTONES <<< "${MILESTONE_LIST}"
          for DAY in $(seq 1 100); do
            IDX=$(( (DAY-1)/7 ))
            MNUM=${MILESTONES[$IDX]}
            gh issue create \
              --title "[Day $DAY] JS Project" \
              --body-file .github/ISSUE_TEMPLATE/daily.yml \
              --milestone $MNUM \
              --project "100 Days of JS" \
              --label "day-$DAY"
          done
