# .github/workflows/setup-100-days-js.yml
name: "Setup 100 Days JS Project"
on:
  workflow_dispatch:

permissions:
  contents: write        # allow reading/writing code
  issues: write          # allow creating & updating issues
  # If you need broad REST/GraphQL API access beyond these, you can use:
  # permissions: write-all

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    # Provide your PAT so gh CLI can create projects
    env:
      GH_TOKEN: ${{ secrets.PAT_PROJECTS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Create Project Board
        id: project
        run: |
          PROJECT_JSON=$(gh project create \
            --owner "${{ github.repository_owner }}" \
            --title "100 Days of JS" \
            --format json)
          echo "PROJECT_NUMBER=$(echo $PROJECT_JSON | jq -r '.number')" >> $GITHUB_ENV

      - name: Create Weekly Milestones
        id: milestones
        run: |
          for WEEK in $(seq 1 14); do
            gh api repos/${{ github.repository }}/milestones \
              -f title="Week $WEEK" \
              -f description="Days $(( (WEEK-1)*7 + 1 ))–$(( WEEK*7 ))" \
              --jq '.number' >> ms.txt
          done
          echo "MILESTONE_LIST=$(paste -sd, ms.txt)" >> $GITHUB_ENV

      - name: Create Day Issues & Add to Project
        run: |
          IFS=, read -r -a MILESTONES <<< "${MILESTONE_LIST}"
          for DAY in $(seq 1 100); do
            IDX=$(( (DAY-1)/7 ))
            MNUM=${MILESTONES[$IDX]}
            ISSUE=$(gh issue create \
              --title "[Day $DAY] JS Project" \
              --body-file .github/ISSUE_TEMPLATE/daily.yml \
              --milestone $MNUM \
              --label "day-$DAY" \
              --format json)
            NUM=$(echo $ISSUE | jq -r '.number')
            gh project item-add $PROJECT_NUMBER --issue "${{ github.repository }}#$NUM"
          done
